# Copyright (c) 2020-present, The Johann Web Basic Authors. All Rights Reserved.
# Use of this source code is governed by a BSD-3-clause license that can
# be found in the LICENSE file. See the AUTHORS file for names of contributors.

version: "2.4"
services:
  johann_web:
    volumes:
      - ./:/app
    environment:
      - FLASK_DEBUG=1
      - "RUN=flask run --host=0.0.0.0 --port=80"
    # command: flask run --host=0.0.0.0 --port=80
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
